spring:
  application:
    name: Sales API
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: sboot-db_sales

api-sales:
  client:
    sales:
      url: http://localhost:8082/sales

